spring.application.name=ride-sharing-system
spring.datasource.url=jdbc:postgresql://localhost:5432/rideshare
spring.datasource.username=postgres
spring.datasource.password=***REMOVED***
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect